Get OS image and check if Redox installed

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,8 +7,6 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    env:
-      COOKBOOK_REDOXER: $HOME/.cargo/bin/redoxer
 
     steps:
       - name: Checkout NexionOS source
@@ -23,15 +21,25 @@ jobs:
           sudo apt update
           sudo apt install -y build-essential qemu-system-x86 podman pkg-config libfuse3-dev libfuse-dev curl
 
-      - name: Install Rust, Install Redoxer
+      - name: Install Rust and Redoxer
         run: |
+          # Install Rust
           curl https://sh.rustup.rs -sSf | sh -s -- -y
           source $HOME/.cargo/env
           echo "$HOME/.cargo/bin" >> $GITHUB_PATH
+
+          # Install Redoxer
           cargo install redoxer --locked
 
+      - name: Debug Redoxer path
+        run: |
+          which redoxer || echo "Redoxer not found in PATH"
+          ls -l $HOME/.cargo/bin/redoxer || echo "Binary missing"
+
       - name: Build OS image
-        run: make image
+        run: |
+          # Force COOKBOOK_REDOXER into make
+          make image COOKBOOK_REDOXER=$HOME/.cargo/bin/redoxer
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
